#!/usr/bin/env rake
# -*- coding: utf-8 -*-

desc "VoiceMemoアプリケーション用のタスク"

namespace :test do
  desc "全てのユニットテストを実行"
  task :all do
    sh "cd #{File.dirname(__FILE__)} && python3 -m unittest discover -s tests -v"
  end

  desc "voice_sync のテストを実行"
  task :sync do
    sh "cd #{File.dirname(__FILE__)} && python3 -m unittest tests.test_voice_sync -v"
  end

  desc "voice_trans のテストを実行"
  task :trans do
    sh "cd #{File.dirname(__FILE__)} && python3 -m unittest tests.test_voice_trans -v"
  end
end

namespace :run do
  desc "ボイスレコーダーからMP3ファイルを同期"
  task :sync do
    sh "cd #{File.dirname(__FILE__)} && python3 -m src.voice_sync"
  end

  desc "MP3ファイルをテキストに変換"
  task :trans do
    sh "cd #{File.dirname(__FILE__)} && python3 -m src.voice_trans"
  end

  desc "同期してからテキスト変換を実行"
  task :all => ['run:sync', 'run:trans'] do
    puts "同期とテキスト変換が完了しました"
  end

  desc "Voice Memoアプリを実行"
  task :app do
    sh "cd #{File.dirname(__FILE__)} && python3 -m src.voice_memo_app"
  end
  
  desc "py2appを使用してアプリをビルド"
  task :build do
    sh "cd #{File.dirname(__FILE__)} && python3 setup.py py2app"
  end
end

task :default => "test:all"
